markdown: kramdown
permalink: /:year/:month/:title
url: https://condy0919.github.io
name: Youmu's home
description: 萌萌的妖妖梦酱
author: condy
qq: 10086
twitter: CondyChen
email: condy0919@gmail.com
weibo: 1659167514
github: condy0919
highlighter: pygments
safe: true
paginate: 20
img_url: https://condy0919.github.io/assets/images
code_dir: /assets/code
about: "我太渣了……"
