markdown: kramdown
permalink: /:year/:month/:title
url: https://condy0919.github.io
name: Youmu's home
description: 喵喵反抗大队队长
author: condy
twitter: CondyChen
email: condy0919@gmail.com
github: condy0919
highlighter: rouge
safe: true
paginate: 20
img_url: https://condy0919.github.io/assets/images
code_dir: /assets/code
about: "我太渣了……"
