markdown: kramdown
permalink: /:year/:month/:day/:title/
url: https://condy0919.github.io/
name: LessIsMore
description: 喵喵反抗大队队长
author: condy
twitter: https://twitter.com/CondyChen
github: https://github.com/condy0919/
email: condy0919@gmail.com
disqus: condy0919
highlighter: rouge
safe: true
paginate: 20
motto: keep moving
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
